# Generated by Django 3.1.7 on 2023-07-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(default=None)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=250)),
                ('district', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
            ],
        ),
    ]
